### ISSUE TITLE
embed doc/images/autocrypthappy.svg in doc/examples.rst

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#10]
I'm unable to get doc/images/autocrypthappy.svg to display in the "examples" html output.

I've tried a change like this:

 ```
--- a/doc/examples.rst
+++ b/doc/examples.rst
@@ -52,6 +52,8 @@ Establishing encryption happens as a side effect when people send each other mai
 "Happy path" example: 1:1 communication
 ---------------------------------------
 
+.. image:: images/autocrypthappy.svg
+
 Consider a blank state and a first outgoing message from Alice to Bob::
 
     From: alice@a.example
```

but when i do that sphinx throws an exception :(

```
# Sphinx version: 1.4.8
# Python version: 2.7.13rc1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   /home/dkg/src/autocrypt/autocrypt/doc/glossary.rst:: WARNING: document isn't included in any toctree
#   /home/dkg/src/autocrypt/autocrypt/doc/level0.rst:: WARNING: document isn't included in any toctree
#   /home/dkg/src/autocrypt/autocrypt/doc/next-steps.rst:: WARNING: document isn't included in any toctree
#   /home/dkg/src/autocrypt/autocrypt/doc/other-crypto-interop.rst:: WARNING: document isn't included in any toctree
#   /home/dkg/src/autocrypt/autocrypt/doc/peering.rst:: WARNING: document isn't included in any toctree
#   /home/dkg/src/autocrypt/autocrypt/doc/ui-examples.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
#   done
#   writing output... [ 50%] examples
# Loaded extensions:
#   sphinx.ext.todo (1.4.8) from /usr/lib/python2.7/dist-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.4.8) from /usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
#   alabaster (0.7.8) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinx.ext.viewcode (1.4.8) from /usr/lib/python2.7/dist-packages/sphinx/ext/viewcode.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 448, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 47, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

@hpk42 maybe you can fix this so that we can include Nico's diagram?

**Comment by dkg** [comment]
just to be clear, i do not want to include generated files in the git repo.  And i'd rather include the svg directly, rather than including a rasterized version of it.  including the svg means that generated files will have searchable text, and they'll be zoomable without any degradation.

**Comment by dkg** [comment]
I just upgraded my install of sphinx from 1.4.8 to 1.4.9, and now the inclusion works fine.

It's also published fine on https://autocrypt.readthedocs.io/en/latest/examples.html !
